apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-rhtap-mc-unsuported-runtime-youd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-rhtap-mc-unsuported-runtime-youd
    app.kubernetes.io/part-of: mc-unsupported-runtime
  name: devfile-sample-python-basic-rhtap-mc-unsuported-runtime-youd
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-rhtap-mc-unsuported-runtime-youd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-rhtap-mc-unsuported-runtime-youd
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-uzmx-tenant/mc-unsupported-runtime/devfile-sample-python-basic-rhtap-mc-unsuported-runtime-youd@sha256:067453a2000bbe3c3453a98a97b8a99c50a4ac427ee85ccfcd8f0b41c4f50ef0
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
